### ISSUE TITLE
运行错误，可以帮忙看下么

### ISSUE THREAD

**Issue by zsray110** [YCYAX/On-screen-real-time-translation#2]
import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by YCYAX** [comment]
>  import cv2
> ModuleNotFoundError: No module named 'cv2'

抱歉，最近比较忙没怎么看github。这个问题是没有安装正确的库，请使用pip install opencv-python。如果安装了库那就是解释器没有设置好。
